name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello World"
          echo "Multi line commands"
      - name: Print Goodbye
        run: echo "Byebye"
